# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths:
      - "**.cs"
  pull_request:
    paths:
      - "**.cs"
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        path: src/bin/Release/net8.0/publish
