name: Update SDK

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_sdk:
    name: Update SDK
    runs-on: macos-13
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3.0.2

      - name: Update submodules
        run: |
          git submodule update --init --remote
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update SDK" || exit 0
          git push || exit 0
